# -*- coding: utf-8 -*-
"""
/***************************************************************************
 knGML2GPKG
                                 A QGIS plugin
 knGML2GPKG
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-27
        copyright            : (C) 2025 by cabaj
        email                : jan807931@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load knGML2GPKG class from file knGML2GPKG.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .knGML2GPKG import knGML2GPKG
    return knGML2GPKG(iface)
